kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: employee-cluster
nodes:
   - role: control-plane
     image: kindest/node:v1.29.0

     extraPortMappings:
           - containerPort: 30082
             hostPort: 30082
             protocol: TCP


   - role: worker
     image: kindest/node:v1.29.0

   - role: worker
     image: kindest/node:v1.29.0


